name = "blackcrypt-emailsender"
compatibility_date = "2024-08-21"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run pages:build"

[[build.environment_variables]]
NODE_VERSION = "18"

[env.production]
compatibility_date = "2024-08-21"
